// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1) {
  return window['go']['main']['App']['AddFiles'](arg1);
}

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function ClearCompleted() {
  return window['go']['main']['App']['ClearCompleted']();
}

export function GetJobs() {
  return window['go']['main']['App']['GetJobs']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsFFmpegAvailable() {
  return window['go']['main']['App']['IsFFmpegAvailable']();
}

export function MoveToTrash(arg1) {
  return window['go']['main']['App']['MoveToTrash'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function RevealInFinder(arg1) {
  return window['go']['main']['App']['RevealInFinder'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
