// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {queue} from '../models';
import {cleanup} from '../models';
import {settings} from '../models';

export function AddFiles(arg1:Array<string>):Promise<Array<queue.Job>>;

export function Cleanup():Promise<cleanup.Result>;

export function ClearCompleted():Promise<void>;

export function GetJobs():Promise<Array<queue.Job>>;

export function GetSettings():Promise<settings.Settings>;

export function IsFFmpegAvailable():Promise<boolean>;

export function MoveToTrash(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFilePicker():Promise<Array<string>>;

export function RevealInFinder(arg1:string):Promise<void>;

export function SaveSettings(arg1:settings.Settings):Promise<void>;
